if AZP == nil then AZP = {} end
if AZP.BagsAndBank == nil then AZP.BagsAndBank = {} end

AZP.BagsAndBank.itemIDs =
{
    [17963]  = {"Green Sack of Gems", "BWL"},
    [17964]  = {"Grey Sack of Gems", "BWL"},
    [17965]  = {"Yellow Sack of Gems", "BWL"},
    [17969]  = {"Red Sack of Gems", "BWL"},
    [20758]  = {"Oozing Bag", "AQ20"},
    [21156]  = {"Scarab Ba", "AQ20"},
    [49294]  = {"Ashen Sack of Gems", "Ony"},
    [153132] = {"Coffer of Argus Equipment", "Legion Missions"},
    [178128] = {"Pouch of Shinies", "Random Drop / PickPocket"},
    [180649] = {"Wild Hunt Supplies", "Covenant Calling"},
    [180981] = {"Novice's Large Satchel", "Queen's Conservatory"},
    [180985] = {"Novice's Stuffed Satchel", "Queen's Conservatory"},
    [180989] = {"Novice's Overflowing Satchel", "Queen's Conservatory"},
    [181372] = {"Tribute of the Ascended", "Covenant Calling"},
    [181475] = {"Bounty of the Grove Wardens", "Covenant Calling"},
    [181476] = {"Tribute of the Wild Hunt", "Covenant Calling"},
    [181556] = {"Tribute of the Court", "Covenant Calling"},
    [181557] = {"Favour of the Court", "Covenant Calling"},
    [181732] = {"Tribute of Ambitious", "Covenant Calling"},
    [181733] = {"Tribute of the Duty-Bound", "Covenant Calling"},
    [181741] = {"Tribute of the Paragon", "Covenant Calling"},
    [183702] = {"Nature's Splendor", "NF, Soulbind"},
    [184395] = {"Fallen Adventurer's Cache", "Maw"},
    [184632] = {"Champion's Fish Cache", "SL Missions"},
    [184637] = {"Hero's Meat Cache", "SL Missions"},
    [184638] = {"Hero's Fishing Cache", "SL Missions"},
    [184639] = {"Champion's Tailoring Cache", "SL Missions"},
    [184640] = {"Champion's Skinning Cache", "SL Missions"},
    [184641] = {"Champion's Mining Cache", "SL Missions"},
    [184642] = {"Champion's Herbalism Cache", "SL Missions"},
    [184643] = {"Champion's Enchanting Cache", "SL Missions"},
    [184646] = {"Hero's Mining Cache", "SL Missions"},
    [185765] = {"Shipment of Heavy Callous Hide", "Valor Vendor"},
    [185832] = {"Shipment of Elethium Ore", "Valor Vendor"},
    [185833] = {"Shipment of Lightless Silk", "Valor Vendor"},
    [185993] = {"Ascended War Chest", "Covenant Assault"},
    [187221] = {"Soul Ash Cache", "Valor Vendor"},
    [187222] = {"Stygic Singularity", "Valor Vendor"},
    [187254] = {"Arrangement of Anima", "Valor Vendor"},
    [187278] = {"Talon-Pierced Mawsworn Lockbox", "Korthia Rare Drop"},
    [187440] = {"Feather-Stuffed Helm", "Korthia Treassure"},
    [187503] = {"Bundle of Archived Research", "Valor Vendor"},
    [184522] = {"Veiled Satchel of Cooperation", "Call To Arms Dungeon"},
    [187569] = {"Brokers' Tailoring Mote of Potentiation", "SL Missions"},
    [186691] = {"Gold Filled Satchel", "Korthia Dailies"},
    [187573] = {"Brokers' Enchanting Mote of Potentiation", "SL Missions"},
    [187574] = {"Brokers' Overflowing Bucket", "Korthia Dailies"},
    [187551] = {"Small Korthian Supply Chest", "Korthia Dailies"},
    [185972] = {"Tormentor's Cache", "Weekly Maw Boss"},
    [186196] = {"Death's Advance War chest", "Korthia Weekly"},
    [180647] = {"Ascended Supplies", "Kyrian Paragon"},
}