if AZP == nil then AZP = {} end
if AZP.BagsAndBank == nil then AZP.BagsAndBank = {} end

AZP.BagsAndBank.itemIDs =
{
      [5523] = {Name =                     "Small Barnacled Clam", Source =         "Enemies On Beach"},
     [17963] = {Name =                       "Green Sack of Gems", Source =           "BlackWing Lair"},
     [17964] = {Name =                        "Grey Sack of Gems", Source =           "BlackWing Lair"},
     [17965] = {Name =                      "Yellow Sack of Gems", Source =           "BlackWing Lair"},
     [17969] = {Name =                         "Red Sack of Gems", Source =           "BlackWing Lair"},
     [20758] = {Name =                               "Oozing Bag", Source =          "Ahn'Qiraj Ruins"},
     [21156] = {Name =                               "Scarab Bag", Source =          "Ahn'Qiraj Ruins"},
     [49294] = {Name =                       "Ashen Sack of Gems", Source =            "Onyxia's Lair"},
    [153132] = {Name =                "Coffer of Argus Equipment", Source =          "Legion Missions"},
    [171211] = {Name =                     "Venthyr's Coin Purse", Source =                 "Torghast"},
    [178128] = {Name =                         "Pouch of Shinies", Source = "Random Drop / PickPocket"},
    [180647] = {Name =                        "Ascended Supplies", Source =           "Kyrian Paragon"},
    [180648] = {Name =             "Court of Harvesters Supplies", Source =        "Necrolord Paragon"},
    [180649] = {Name =                       "Wild Hunt Supplies", Source =         "Covenant Calling"},
    [180976] = {Name =                       "Artisian's Satchel", Source =     "Queen's Conservatory"},
    [180977] = {Name =                  "Spirit-Tender's Satchel", Source =     "Queen's Conservatory"},
    [180980] = {Name =               "Journeyman's Large Satchel", Source =     "Queen's Conservatory"},
    [180981] = {Name =                   "Novice's Large Satchel", Source =     "Queen's Conservatory"},
    [180984] = {Name =             "Journeyman's Stuffed Satchel", Source =     "Queen's Conservatory"},
    [180985] = {Name =                 "Novice's Stuffed Satchel", Source =     "Queen's Conservatory"},
    [180989] = {Name =             "Novice's Overflowing Satchel", Source =     "Queen's Conservatory"},
    [181372] = {Name =                  "Tribute of the Ascended", Source =         "Covenant Calling"},
    [181475] = {Name =              "Bounty of the Grove Wardens", Source =         "Covenant Calling"},
    [181476] = {Name =                 "Tribute of the Wild Hunt", Source =         "Covenant Calling"},
    [181556] = {Name =                     "Tribute of the Court", Source =         "Covenant Calling"},
    [181557] = {Name =                      "Favour of the Court", Source =         "Covenant Calling"},
    [181732] = {Name =                     "Tribute of Ambitious", Source =         "Covenant Calling"},
    [181733] = {Name =                "Tribute of the Duty-Bound", Source =         "Covenant Calling"},
    [181741] = {Name =                   "Tribute of the Paragon", Source =         "Covenant Calling"},
    [183702] = {Name =                        "Nature's Splendor", Source =        "NightFae Soulbind"},
    [184395] = {Name =                "Fallen Adventurer's Cache", Source =                  "The Maw"},
    [184522] = {Name =            "Veiled Satchel of Cooperation", Source =     "Call To Arms Dungeon"},
    [184632] = {Name =                    "Champion's Fish Cache", Source =     "Shadowlands Missions"},
    [184637] = {Name =                        "Hero's Meat Cache", Source =     "Shadowlands Missions"},
    [184638] = {Name =                     "Hero's Fishing Cache", Source =     "Shadowlands Missions"},
    [184639] = {Name =               "Champion's Tailoring Cache", Source =     "Shadowlands Missions"},
    [184640] = {Name =                "Champion's Skinning Cache", Source =     "Shadowlands Missions"},
    [184641] = {Name =                  "Champion's Mining Cache", Source =     "Shadowlands Missions"},
    [184642] = {Name =               "Champion's Herbalism Cache", Source =     "Shadowlands Missions"},
    [184643] = {Name =              "Champion's Enchanting Cache", Source =     "Shadowlands Missions"},
    [184646] = {Name =                      "Hero's Mining Cache", Source =     "Shadowlands Missions"},
    [185765] = {Name =           "Shipment of Heavy Callous Hide", Source =             "Valor Vendor"},
    [185832] = {Name =                 "Shipment of Elethium Ore", Source =             "Valor Vendor"},
    [185833] = {Name =               "Shipment of Lightless Silk", Source =             "Valor Vendor"},
    [185972] = {Name =                        "Tormentor's Cache", Source =          "Weekly Maw Boss"},
    [185992] = {Name =            "War Chest of the Undying Army", Source =              "Maw Assault"},
    [185993] = {Name =                       "Ascended War Chest", Source =         "Covenant Assault"},
    [186196] = {Name =                "Death's Advance War chest", Source =           "Korthia Weekly"},
    [186691] = {Name =                      "Gold Filled Satchel", Source =          "Korthia Dailies"},
    [186707] = {Name =                        "Gold Filled Crate", Source =          "Korthia Dailies"},
    [186708] = {Name =              "Gold Filled Paint Brush Cup", Source =          "Korthia Dailies"},
    [187221] = {Name =                           "Soul Ash Cache", Source =             "Valor Vendor"},
    [187222] = {Name =                       "Stygic Singularity", Source =             "Valor Vendor"},
    [187254] = {Name =                     "Arrangement of Anima", Source =             "Valor Vendor"},
    [187278] = {Name =           "Talon-Pierced Mawsworn Lockbox", Source =        "Korthia Rare Drop"},
    [187440] = {Name =                     "Feather-Stuffed Helm", Source =        "Korthia Treassure"},
    [187503] = {Name =              "Bundle of Archived Research", Source =             "Valor Vendor"},
    [187551] = {Name =              "Small Korthian Supply Chest", Source =          "Korthia Dailies"},
    [187569] = {Name =  "Brokers' Tailoring Mote of Potentiation", Source =     "Shadowlands Missions"},
    [187573] = {Name = "Brokers' Enchanting Mote of Potentiation", Source =     "Shadowlands Missions"},
    [187574] = {Name =              "Brokers' Overflowing Bucket", Source =          "Korthia Dailies"},
    [187576] = {Name =                  "Korthian Skinning Cache", Source =     "Shadowlands Missions"},
}