if AZP == nil then AZP = {} end
if AZP.UseItems == nil then AZP.UseItems = {} end

AZP.UseItems.itemIDs =
{
    [20758]  = {"Oozing Bag", "AQ20"},
    [21156]  = {"Scarab Ba", "AQ20"},
    [17965]  = {"Yellow Sack of Gems", "BWL"},
    [49294]  = {"Ashen Sack of Gems", "Ony"},
    [17964]  = {"Grey Sack of Gems", "BWL"},
    [17969]  = {"Red Sack of Gems", "BWL"},
    [17963]  = {"Green Sack of Gems", "BWL"},
    [183702] = {"Nature's Splendor", "NF, Soulbind"},
    [181475] = {"Bounty of the Grove Wardens", "Covenant Calling"},
    [184637] = {"Hero's Meat Cache", "SL Missions"},
    [184632] = {"Champion's Fish Cache", "SL Missions"},
    [184643] = {"Champion's Enchanting Cache", "SL Missions"},
    [153132] = {"Coffer of Argus Equipment", "Legion Missions"},
    [181556] = {"Tribute of the Court", "Covenant Calling"},
    [181741] = {"Tribute of the Paragon", "Covenant Calling"},
    [181372] = {"Tribute of the Ascended", "Covenant Calling"},
    [184640] = {"Champion's Skinning Cache", "SL Missions"},
    [184638] = {"Hero's Fishing Cache", "SL Missions"},
    [181733] = {"Tribute of the Duty-Bound", "Covenant Calling"},
    [181476] = {"Tribute of the Wild Hunt", "Covenant Calling"},
    [180649] = {"Wild Hunt Supplies", "Covenant Calling"},
    [184639] = {"Champion's Tailoring Cache", "SL Missions"},
    [181732] = {"Tribute of Ambitious", "Covenant Calling"},
    [184646] = {"Hero's Mining Cache", "SL Missions"},
    [184642] = {"Champion's Herbalism Cache", "SL Missions"},
    [184641] = {"Champion's Mining Cache", "SL Missions"},
    [178128] = {"Pouch of Shinies", "Random Drop / PickPocket"},
    [181557] = {"Favour of the Court", "Covenant Calling"},
    [180989] = {"Novice's Overflowing Satchel", "Queen's Conservatory"},
    [180981] = {"Novice's Large Satchel", "Queen's Conservatory"},
    [184395] = {"Fallen Adventurer's Cache", "Maw"},
    [180985] = {"Novice's Stuffed Satchel", "Queen's Conservatory"},
}